-- SQL para la creación de la tabla SnibGeoportal
CREATE TABLE `SnibGeoportal` (
`grupobio` varchar(50) NOT NULL DEFAULT '',
`subgrupobio` varchar(250) NOT NULL DEFAULT '',
`familiavalida` varchar(50) NOT NULL DEFAULT '',
`generovalido` varchar(50) NOT NULL DEFAULT '',
`especievalida` varchar(100) NOT NULL DEFAULT '',
`nom059` varchar(512) NOT NULL DEFAULT '',
`cites` varchar(512) NOT NULL DEFAULT '',
`iucn` varchar(1024) NOT NULL DEFAULT '',
`prioritaria` varchar(100) NOT NULL DEFAULT '',
`exoticainvasora` varchar(50) NOT NULL DEFAULT '',
`longitud` double DEFAULT NULL,
`latitud` double DEFAULT NULL,
`estadomapa` varchar(50) NOT NULL DEFAULT '',
`municipiomapa` varchar(80) NOT NULL DEFAULT '',
`localidad` varchar(2048) NOT NULL DEFAULT '',
`fechacolecta` varchar(10) NOT NULL DEFAULT '',
`anp` varchar(250) NOT NULL DEFAULT '',
`categoriaresidenciaaves` varchar(100) NOT NULL DEFAULT '',
`formadecrecimiento` varchar(100) NOT NULL DEFAULT '',
`fuente` varchar(50) NOT NULL DEFAULT '',
`taxonextinto` enum('', 'SI', 'NO') NOT NULL DEFAULT '',
`usvserieVII` varchar(100) NOT NULL DEFAULT '',
`vegetacionserenanalcms` varchar(70) NOT NULL DEFAULT '',
`urlejemplar` varchar(255) NOT NULL DEFAULT '',
`idejemplar` varchar(32) NOT NULL DEFAULT '',
`ultimafechaactualizacion` date DEFAULT NULL,
`idnombrecatvalido` varchar(50) NOT NULL DEFAULT '',
`idnombrecat` varchar(50) NOT NULL DEFAULT '',
`reino` varchar(50) NOT NULL DEFAULT '',
`phylumdivision` varchar(50) NOT NULL DEFAULT '',
`clase` varchar(50) NOT NULL DEFAULT '',
`orden` varchar(50) NOT NULL DEFAULT '',
`familia` varchar(50) NOT NULL DEFAULT '',
`genero` varchar(50) NOT NULL DEFAULT '',
`especie` varchar(100) NOT NULL DEFAULT '',
`calificadordeterminacion` varchar(100) NOT NULL DEFAULT '',
`categoriainfraespecie` varchar(50) NOT NULL DEFAULT '',
`categoriainfraespecie2` varchar(50) NOT NULL DEFAULT '',
`autor` longtext NOT NULL,
`estatustax` varchar(20) NOT NULL DEFAULT '',
`reftax` varchar(255) NOT NULL DEFAULT '',
`taxonvalidado` varchar(2) NOT NULL DEFAULT '',
`reinovalido` varchar(50) NOT NULL DEFAULT '',
`phylumdivisionvalido` varchar(50) NOT NULL DEFAULT '',
`clasevalida` varchar(50) NOT NULL DEFAULT '',
`ordenvalido` varchar(50) NOT NULL DEFAULT '',
`categoriainfraespecievalida` varchar(50) NOT NULL DEFAULT '',
`categoriainfraespecie2valida` varchar(50) NOT NULL DEFAULT '',
`autorvalido` mediumtext NOT NULL,
`reftaxvalido` varchar(255) NOT NULL DEFAULT '',
`nombrecomun` text NOT NULL,
`ambiente` varchar(100) NOT NULL DEFAULT '',
`validacionambiente` varchar(100) NOT NULL DEFAULT '',
`endemismo` enum('','Cuasiendémica','Endémica','Semiendémica') NOT NULL DEFAULT '',
`nivelprioridad` enum('','Alta','Media','Menor') NOT NULL DEFAULT '',
`region` varchar(150) NOT NULL DEFAULT '',
`datum` varchar(50) NOT NULL DEFAULT '',
`geovalidacion` varchar(200) NOT NULL DEFAULT '',
`paismapa` varchar(50) NOT NULL DEFAULT '',
`claveestadomapa` varchar(10) NOT NULL DEFAULT '',
`mt24claveestadomapa` varchar(10) NOT NULL DEFAULT '',
`mt24nombreestadomapa` varchar(50) NOT NULL DEFAULT '',
`clavemunicipiomapa` varchar(10) NOT NULL DEFAULT '',
`mt24clavemunicipiomapa` varchar(10) NOT NULL DEFAULT '',
`mt24nombremunicipiomapa` varchar(80) NOT NULL DEFAULT '',
`incertidumbreXY` int(11) DEFAULT NULL,
`altitudmapa` smallint(6) DEFAULT NULL,
`usvserieI` varchar(100) NOT NULL DEFAULT '',
`usvserieII` varchar(100) NOT NULL DEFAULT '',
`usvserieIII` varchar(100) NOT NULL DEFAULT '',
`usvserieIV` varchar(100) NOT NULL DEFAULT '',
`usvserieV` varchar(100) NOT NULL DEFAULT '',
`usvserieVI` varchar(100) NOT NULL DEFAULT '',
`coleccion` varchar(150) NOT NULL DEFAULT '',
`institucion` varchar(255) NOT NULL DEFAULT '',
`paiscoleccion` varchar(50) NOT NULL DEFAULT '',
`numcatalogo` varchar(100) NOT NULL DEFAULT '',
`numcolecta` varchar(100) NOT NULL DEFAULT '',
`procedenciaejemplar`enum('','HumanObservation','PreservedSpecimen','FossilSpecimen','MaterialCitation','O
ccurrence','MaterialSample','MachineObservation','LivingSpecimen') NOT NULL DEFAULT '',
`determinador` varchar(512) NOT NULL DEFAULT '',
`fechadeterminacion` varchar(10) NOT NULL DEFAULT '',
`diadeterminacion` tinyint(4) DEFAULT NULL,
`mesdeterminacion` tinyint(4) DEFAULT NULL,
`aniodeterminacion` smallint(6) DEFAULT NULL,
`colector` varchar(512) NOT NULL DEFAULT '',
`diacolecta` tinyint(4) DEFAULT NULL,
`mescolecta` tinyint(4) DEFAULT NULL,
`aniocolecta` smallint(6) DEFAULT NULL,
`tipo` varchar(60) NOT NULL DEFAULT '',
`ejemplarfosil` enum('', 'SI', 'NO') NOT NULL DEFAULT '',
`proyecto` varchar(50) NOT NULL DEFAULT '',
`formadecitar` text NOT NULL,
`licenciauso` varchar(255) NOT NULL DEFAULT '',
`urlproyecto` varchar(255) NOT NULL DEFAULT '',
`urlorigen` varchar(255) NOT NULL DEFAULT '',
`obsusoinfo` varchar(512) NOT NULL DEFAULT '',
`version` varchar(7) NOT NULL DEFAULT '',
`idestadomapa` mediumint(8) DEFAULT NULL,
`idmunicipiomapa` int(10) DEFAULT NULL,
`mt24idestadomapa` mediumint(8) DEFAULT NULL,
`mt24idmunicipiomapa` int(10) DEFAULT NULL,
`idanpfederal1` mediumint(8) DEFAULT NULL,
`idanpfederal2` mediumint(8) DEFAULT NULL,
`especievalidabusqueda` varchar(100) NOT NULL,
`comentarioscat` varchar(1024) NOT NULL,
`comentarioscatvalido` varchar(1024) NOT NULL,
`homonimosgenero` varchar(512) NOT NULL,
`homonimosespecie` text NOT NULL,
`homonimosinfraespecie` varchar(255) NOT NULL,
`homonimosgenerocatvalido` varchar(255) NOT NULL,
`homonimosespeciecatvalido` text NOT NULL,
`homonimosinfraespeciecatvalido` varchar(255) NOT NULL,
`categoriataxonomica` varchar(50) NOT NULL
PRIMARY KEY (`idejemplar`),
KEY `grupobio` (`grupobio`),
KEY `anp` (`anp`),
KEY `latlon` (`longitud`,`latitud`),
KEY `paism` (`paismapa`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8